# Generated by Django 4.1.3 on 2022-11-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_person_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
