# Generated by Django 4.1.3 on 2022-11-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='has_schedule',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
    ]
