# Generated by Django 4.1.3 on 2022-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment_is_accept_appointment_is_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
