# Generated by Django 4.1.3 on 2022-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mybaseuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
