# Generated by Django 4.1.3 on 2022-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mybaseuser_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialties',
            new_name='specialities',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
